name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags like v0.1.0, v1.2.3

permissions:
  contents: read
  # Required for Trusted Publishing: 
  # id-token: write 

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x" # Use a recent Python version for building

    - name: Install build dependencies
      run: python -m pip install build

    - name: Build sdist and wheel
      # Build artifacts in the subdirectory where pyproject.toml is located
      working-directory: ./proctor 
      run: python -m build

    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: proctor/dist/ # Path to the built artifacts relative to workspace root

  publish-to-pypi:
    name: Publish distribution to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/proctor # URL to the package on PyPI (matches repo name)
    # Uncomment if using Trusted Publishing:
    # permissions:
    #   id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/ # Download artifacts to a 'dist' directory
        
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # If using API Token:
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }} 
      # If using Trusted Publishing (preferred):
      # with:
      #   attestations: true
      #   provenance: true 